# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: "millennial-3"

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ""

menu:
  - { name: "About me", url: "https://card.ngocquan.com/" }
  - { name: "Resume", url: "https://ngocquan.com/" }
  - { name: "Images", url: "https://travel.ngocquan.com/" }
  - { name: "Contact", url: "contact" }

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - { icon: "github", link: "https://github.com/ngocquanofficial/" }
  - { icon: "facebook", link: "https://www.facebook.com/ngocquanofficial/" }
  - { icon: "instagram", link: "https://instagram.com/_ngoc_quan_" }
  - { icon: "envelope", link: "mailto:ngocquanofficial@gmail.com" }
  - { icon: "linkedin", link: "https://www.linkedin.com/in/ngocquanofficial/" }

# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: "Newer"
  previous_page: "Older"

sharing_button_prompt: "Feel free to share!"

related_posts: "You may also enjoy..."

post_date_prefix: "Written on"
